<a href="https://colab.research.google.com/github/Jace-Hambrick/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/module2-make-features/JaceH_LS_DS15_112_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [16]:
##### Begin Working Here #####

# !wget to pull the 
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2020-04-07 20:07:46--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 52.27.155.37, 54.212.130.102, 34.214.150.56
Connecting to resources.lendingclub.com (resources.lendingclub.com)|52.27.155.37|:443... connected.
HTTP request sent, awaiting response... ^C

In [17]:
# Unzipping the CSV
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [0]:
import pandas as pd

In [0]:
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_columns', 150)

In [20]:
!head LoanStats_2018Q4.csv

#Has a screwy 'Notes Offered by-' that messes with the Headers

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","35000","35000","35000"," 36 months"," 14.47%","1204.23","C","C2","Staff Physician","8 years","MORTGAGE","360000","Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","336xx","FL","19.9","0","Apr-1995","1","","","24","0","57259","43.2%","51","w","0.00","0.00","38187.0468373662","38187.05","35000.00","3187.05","0.0","0.0","0.0","Aug-2019","29882.16","","Sep-2019","0","","1","Individual","","","","0","0","828060","0","6","1","2","9","112027","29","4","8","19118","36","132400","3","2","5","11","34503","67341","46","0","0","173","284","8","8","3","8","","0","","0","11","11","13","20","23","16","24","11","24","0","0","0","5","100","30.8","0","0","1222051","169286","124600","258401","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 22.35%","191.86","D","D5","Director of Sales","10+ years","MORTGAGE","72000","Source Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","333xx","FL","20.12","0","Mar-2010","0","","","13","0","11720","47.1%","26","f","0.00","0.00","5615.9776735688","5615.98","5000.00","615.98","0.0","0.0","0.0","Jul-2019","4474.13","","Aug-2019","0","","1","Individual","","","","0","534","189279","0","1","0","1","18","22698","","0","0","4056","47","24900","1","0","1","2","14560","8163","55.1","0","0","105","90","29","8","5","40","","9","","0","6","11","6","8","4","11","17","11","13","0","0","0","1","100","50","0","0","218686","34418","18200","37786","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 60 months"," 23.40%","284.21","E","E1","","< 1 year","RENT","55000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","902xx","CA","13.51","0","Apr-2007","0","44","88","9","1","11859","53.9%","11","w","8462.43","8462.43","4243.65","4243.65","1537.57","2706.08","0.0","0.0","0.0","Mar-2020","284.21","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","21235","0","1","0","1","20","9376","76","0","3","3122","62","22000","1","0","0","4","2359","1119","89.3","0","0","140","140","13","13","0","13","","15","44","0","4","7","4","5","2","8","9","7","9","0","0","0","0","90.9","100","1","0","34386","21235","10500","12386","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","17100","17100","17100"," 36 months"," 18.94%","626.3","D","D2","Receptionist ","10+ years","RENT","38000","Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","150xx","PA","38.09","0","Mar-1998","1","47","","14","0","15323","53%","21","w","11120.22","11120.22","9367.51","9367.51","5979.78","3387.73","0.0","0.0","0.0","Mar-2020","626.3","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","43351","1","2","1","1","10","28028","67","1","5","7533","53","29170","0","0","2","6","3096","4150","77","0","0","125","230","5","5","2","5","","5","","0","4","12","5","5","5","12","14","9","14","","0","0","2","95","75","0","0","70954","43351","16600","41784","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 10.72%","130.43","B","B2","Extrusion assistant ","10+ years","MORTGAGE","56000","Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","301xx","GA","31.03","0","Sep-2006","0","","","7","0","4518","28.6%","11","w","2487.19","2487.19","1943.36","1943.36","1512.81","430.55","0.0","0.0","0.0","Mar-2020","130.43","Apr-2020","Mar-2020","1","","1","Individual","","","","0","136","192983","0","2","0","2","14","66857","","0","3","1608","29","15800","3","0","0","5","27569","7835","36.3","0","0","147","29","22","14","1","22","","17","","0","3","4","3","3","6","4","4","4","7","0","0","0","0","100","0","0","0","221310","71375","12300","77865","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10475","10475","10475"," 36 months"," 11.31%","344.48","B","B3","Teacher","6 years","RENT","66150","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","786xx","TX","7.4","0","Jun-1991","0","28","","10","0","10499","40.2%","17","w","6535.06","6535.06","5157.33","5157.33","3939.94","1217.39","0.0","0.0","0.0","Mar-2020","344.48","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","10499","1","0","0","0","84","0","","3","5","3841","40","26100","2","1","5","5","1312","14847","36.8","0","0","88","330","3","3","2","7","","1","28","0","5","8","7","8","2","10","13","8","10","0","0","0","3","88.2","60","0","0","26100","10499","23500","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","7500","7500","7500"," 36 months"," 11.31%","246.65","B","B3","Supervisor","7 years","MORTGAGE","40500","Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","604xx","IL","31.61","0","Sep-1996","1","","","23","0","14218","16.3%","33","w","4862.42","4862.42","3508.34","3508.34","2637.58","855.76","15.0","0.0","0.0","Mar-2020","1016.6","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","123779","3","2","1","1","12","8096","29","3","6","2972","19","87000","0","0","2","7","5626","21078","23.9","0","0","59","267","1","1","1","6","","6","","0","4","6","7","10","2","20","30","6","23","0","0","0","4","100","0","0","0","221569","22314","27700","28409","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","3600","3600","3600"," 36 months"," 11.80%","119.23","B","B4","Analyst","5 years","MORTGAGE","50000","Source Verified","Dec-2018","Fully Paid","n","","","other","Other","427xx","KY","16.11","0","Jan-2002","2","","","10","0","5865","17.4%","17","w","0.00","0.00","4004.1696442235","4004.17","3600.00","404.17","0.0","0.0","0.0","Feb-2020","2678.48","","Mar-2020","0","","1","Individual","","","","0","0","243415","3","3","1","2","3","68184","95","1","3","0","53","33700","2","1","10","6","24342","17300","0","0","0","203","198","4","3","1","18","","3","","1","0","1","4","6","6","6","10","1","10","0","0","0","3","93.8","0","0","0","272629","74049","17300","68929","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [21]:
!tail LoanStats_2018Q4.csv

#has 2 end lines that need to be removed.

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","3235.65","3235.65","3223.02","3223.02","2364.35","858.67","0.0","0.0","0.0","Mar-2020","190.21","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","5831.03","5831.03","5886.58","5886.58","4168.97","1717.61","0.0","0.0","0.0","Mar-2020","346.76","Apr-2020","Mar-2020","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","2888.98","2888.98","2883.34","2883.34","2111.02","772.32","0.0","0.0","0.0","Mar-2020","169.83","Apr-2020","Mar-2020","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","5687.01","5544.84","5555.2","5416.32","4312.99","1242.21","0.0","0.0","0.0","Mar-2020","327.68","Apr-2020","Mar-2020","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","5899.34","5899.34","6043.97","6043.97","4100.66","1943.31","0.0","0.0","0.0","Mar-2020","356.08","Apr-2020","Mar-2020","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [22]:
df = pd.read_csv('LoanStats_2018Q4.csv', header=1)

print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128414, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,35000.0,35000.0,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,336xx,FL,19.90,0.0,Apr-1995,1.0,NaN,NaN,24.0,0.0,57259.0,43.2%,51.0,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,828060.0,0.0,6.0,1.0,2.0,9.0,112027.0,29.0,4.0,8.0,19118.0,36.0,132400.0,3.0,2.0,5.0,11.0,34503.0,67341.0,46.0,0.0,0.0,173.0,284.0,8.0,8.0,3.0,8.0,NaN,0.0,NaN,0.0,11.0,11.0,13.0,20.0,23.0,16.0,24.0,11.0,24.0,0.0,0.0,0.0,5.0,100.0,30.8,0.0,0.0,1222051.0,169286.0,124600.0,258401.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,5000.0,5000.0,5000.0,36 months,22.35%,191.86,D,D5,Director of Sales,10+ years,MORTGAGE,72000.0,Source Verified,Dec-2018,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,333xx,FL,20.12,0.0,Mar-2010,0.0,NaN,NaN,13.0,0.0,11720.0,47.1%,26.0,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,534.0,189279.0,0.0,1.0,0.0,1.0,18.0,22698.0,NaN,0.0,0.0,4056.0,47.0,24900.0,1.0,0.0,1.0,2.0,14560.0,8163.0,55.1,0.0,0.0,105.0,90.0,29.0,8.0,5.0,40.0,NaN,9.0,NaN,0.0,6.0,11.0,6.0,8.0,4.0,11.0,17.0,11.0,13.0,0.0,0.0,0.0,1.0,100.0,50.0,0.0,0.0,218686.0,34418.0,18200.0,37786.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,10000.0,10000.0,10000.0,60 months,23.40%,284.21,E,E1,NaN,< 1 year,RENT,55000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,902xx,CA,13.51,0.0,Apr-2007,0.0,44.0,88.0,9.0,1.0,11859.0,53.9%,11.0,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,21235.0,0.0,1.0,0.0,1.0,20.0,9376.0,76.0,0.0,3.0,3122.0,62.0,22000.0,1.0,0.0,0.0,4.0,2359.0,1119.0,89.3,0.0,0.0,140.0,140.0,13.0,13.0,0.0,13.0,NaN,15.0,44.0,0.0,4.0,7.0,4.0,5.0,2.0,8.0,9.0,7.0,9.0,0.0,0.0,0.0,0.0,90.9,100.0,1.0,0.0,34386.0,21235.0,10500.0,12386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,17100.0,17100.0,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,150xx,PA,38.09,0.0,Mar-1998,1.0,47.0,NaN,14.0,0.0,15323.0,53%,21.0,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,43351.0,1.0,2.0,1.0,1.0,10.0,28028.0,67.0,1.0,5.0,7533.0,53.0,29170.0,0.0,0.0,2.0,6.0,3096.0,4150.0,77.0,0.0,0.0,125.0,230.0,5.0,5.0,2.0,5.0,NaN,5.0,NaN,0.0,4.0,12.0,5.0,5.0,5.0,12.0,14.0,9.0,14.0,NaN,0.0,0.0,2.0,95.0,75.0,0.0,0.0,70954.0,43351.0,16600.0,41784.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,4000.0,4000.0,4000.0,36 months,10.72%,130.43,B,B2,Extrusion assistant,10+ years,MORTGAGE,56000.0,Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,301xx,GA,31.03,0.0,Sep-2006,0.0,NaN,NaN,7.0,0.0,4518.0,28.6%,11.0,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,136.0,192983.0,0.0,2.0,0.0,2.0,14.0,66857.0,NaN,0.0,3.0,1608.0,29.0,15800.0,3.0,0.0,0.0,5.0,27569.0,7835.0,36.3,0.0,0.0,147.0,29.0,22.0,14.0,1.0,22.0,NaN,17.0,NaN,0.0,3.0,4.0,3.0,3.0,6.0,4.0,4.0,4.0,7.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,221310.0,71375.0,12300.0,77865.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df = pd.read_csv('LoanStats_2018Q4.csv', skiprows=1, skipfooter=2)
                 
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

(128412, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,336xx,FL,19.90,0,Apr-1995,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,828060,0,6,1,2,9.0,112027,29.0,4,8,19118,36.0,132400,3,2,5,11,34503.0,67341.0,46.0,0,0,173.0,284,8,8,3,8.0,NaN,0.0,NaN,0,11,11,13,20,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director of Sales,10+ years,MORTGAGE,72000.0,Source Verified,Dec-2018,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,Mar-2010,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,534,189279,0,1,0,1,18.0,22698,NaN,0,0,4056,47.0,24900,1,0,1,2,14560.0,8163.0,55.1,0,0,105.0,90,29,8,5,40.0,NaN,9.0,NaN,0,6,11,6,8,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,NaN,< 1 year,RENT,55000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,Apr-2007,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,21235,0,1,0,1,20.0,9376,76.0,0,3,3122,62.0,22000,1,0,0,4,2359.0,1119.0,89.3,0,0,140.0,140,13,13,0,13.0,NaN,15.0,44.0,0,4,7,4,5,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,Mar-1998,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,43351,1,2,1,1,10.0,28028,67.0,1,5,7533,53.0,29170,0,0,2,6,3096.0,4150.0,77.0,0,0,125.0,230,5,5,2,5.0,NaN,5.0,NaN,0,4,12,5,5,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion assistant,10+ years,MORTGAGE,56000.0,Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,301xx,GA,31.03,0,Sep-2006,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,NaN,NaN,0,136,192983,0,2,0,2,14.0,66857,NaN,0,3,1608,29.0,15800,3,0,0,5,27569.0,7835.0,36.3,0,0,147.0,29,22,14,1,22.0,NaN,17.0,NaN,0,3,4,3,3,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# suming null values
df.isnull().sum().sort_values()

inq_fi                                             0
delinq_amnt                                        0
chargeoff_within_12_mths                           0
acc_open_past_24mths                               0
inq_last_12m                                       0
total_cu_tl                                        0
total_rev_hi_lim                                   0
max_bal_bc                                         0
open_rv_24m                                        0
open_rv_12m                                        0
total_bal_il                                       0
open_il_24m                                        0
hardship_flag                                      0
open_act_il                                        0
open_acc_6m                                        0
tot_cur_bal                                        0
tot_coll_amt                                       0
acc_now_delinq                                     0
application_type                                   0
policy_code                                        0
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_rcnt_tl                                     0
mort_acc                                           0
total_il_high_credit_limit                         0
total_bc_limit                                     0
total_bal_ex_mort                                  0
tot_hi_cred_lim                                    0
tax_liens                                          0
pub_rec_bankruptcies                               0
pct_tl_nvr_dlq                                     0
num_tl_op_past_12m                                 0
num_tl_90g_dpd_24m                                 0
collections_12_mths_ex_med                         0
num_tl_30dpd                                       0
num_rev_tl_bal_gt_0                                0
num_rev_accts                                      0
num_op_rev_tl                                      0
num_il_tl                                          0
num_bc_tl                                          0
num_bc_sats                                        0
num_actv_rev_tl                                    0
num_actv_bc_tl                                     0
num_accts_ever_120_pd                              0
num_sats                                           0
last_pymnt_amnt                                    0
open_il_12m                                        0
debt_settlement_flag                               0
pub_rec                                            0
open_acc                                           0
grade                                              0
sub_grade                                          0
home_ownership                                     0
inq_last_6mths                                     0
annual_inc                                         0
verification_status                                0
earliest_cr_line                                   0
delinq_2yrs                                        0
issue_d                                            0
addr_state                                         0
zip_code                                           0
title                                              0
loan_status                                        0
pymnt_plan                                         0
installment                                        0
revol_bal                                          0
term                                               0
collection_recovery_fee                            0
loan_amnt                                          0
recoveries                                         0
total_rec_late_fee                                 0
funded_amnt                                        0
funded_amnt_inv                                    0
total_acc                                          0
total_rec_int                                      0
purpose                                            0
total_rec_prncp                                    0
total_pymnt_inv                                    0
total_pymnt                                        0
out_prncp_inv                                      0
out_prncp                                          0
initial_list_status                                0
int_rate                                           0
last_credit_pull_d                                 1
avg_cur_bal                                       13
all_util                                          37
revol_util                                       156
last_pymnt_d                                     159
dti                                              237
mths_since_recent_bc                            1591
bc_open_to_buy                                  1691
percent_bc_gt_75                                1692
bc_util                                         1754
num_tl_120dpd_2m                                2859
mths_since_rcnt_il                              4478
mo_sin_old_il_acct                              4478
emp_length                                     11704
mths_since_recent_inq                          16047
il_util                                        20274
emp_title                                      20947
next_pymnt_d                                   34634
mths_since_last_delinq                         72196
mths_since_recent_revol_delinq                 91630
mths_since_last_major_derog                    99232
mths_since_recent_bc_dlq                      103243
sec_app_open_acc                              111630
sec_app_mort_acc                              111630
sec_app_inq_last_6mths                        111630
sec_app_earliest_cr_line                      111630
revol_bal_joint                               111630
sec_app_open_act_il                           111630
annual_inc_joint                              111630
dti_joint                                     111630
sec_app_collections_12_mths_ex_med            111630
sec_app_chargeoff_within_12_mths              111630
sec_app_num_rev_accts                         111630
sec_app_revol_util                            111888
mths_since_last_record                        112962
verification_status_joint                     113564
sec_app_mths_since_last_major_derog           123258
debt_settlement_flag_date                     127672
settlement_date                               127672
settlement_amount                             127672
settlement_status                             127672
settlement_term                               127672
settlement_percentage                         127672
hardship_status                               128100
deferral_term                                 128100
hardship_amount                               128100
hardship_start_date                           128100
hardship_end_date                             128100
payment_plan_start_date                       128100
hardship_length                               128100
hardship_dpd                                  128100
hardship_loan_status                          128100
hardship_reason                               128100
hardship_payoff_balance_amount                128100
hardship_last_payment_amount                  128100
hardship_type                                 128100
orig_projected_additional_accrued_interest    128153
url                                           128412
member_id                                     128412
desc                                          128412
id                                            128412
dtype: int64

In [26]:
df.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
128407,NaN,NaN,23000,23000,23000.0,36 months,15.02%,797.53,C,C3,Tax Consultant,10+ years,MORTGAGE,75000.0,Source Verified,Oct-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,352xx,AL,20.95,1,Aug-1985,2,22.0,NaN,12,0,22465,43.6%,28,w,0.00,0.00,1547.08,1547.08,1025.67,521.41,0.0,0.0,0.0,Dec-2018,797.53,NaN,Nov-2018,0,NaN,1,Individual,NaN,NaN,NaN,0,0,259658,4,2,3,3,6.0,18149,86.0,4,6,12843,56.0,51500,2,2,5,11,21638.0,26321.0,44.1,0,0,12.0,397,4,4,6,5.0,22.0,4.0,22.0,0,4,5,7,14,3,9,19,5,12,0.0,0,0,7,96.4,14.3,0,0,296500,40614,47100,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128408,NaN,NaN,10000,10000,10000.0,36 months,15.02%,346.76,C,C3,security guard,5 years,MORTGAGE,38000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,443xx,OH,13.16,3,Jul-1982,0,6.0,NaN,11,0,5634,37.1%,16,w,5831.03,5831.03,5886.58,5886.58,4168.97,1717.61,0.0,0.0,0.0,Mar-2020,346.76,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,155,77424,0,1,0,0,34.0,200,10.0,1,1,1866,42.0,15200,2,0,0,2,7039.0,4537.0,50.1,0,0,34.0,434,11,11,3,11.0,6.0,17.0,6.0,0,3,5,5,6,1,8,11,5,11,0.0,0,0,1,73.3,40.0,0,0,91403,9323,9100,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128409,NaN,NaN,5000,5000,5000.0,36 months,13.56%,169.83,C,C1,Payoff Clerk,10+ years,MORTGAGE,35360.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,381xx,TN,11.30,1,Jun-2006,0,21.0,NaN,9,0,2597,27.3%,15,f,2888.98,2888.98,2883.34,2883.34,2111.02,772.32,0.0,0.0,0.0,Mar-2020,169.83,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,1413,69785,0,2,0,1,16.0,2379,40.0,3,4,1826,32.0,9500,0,0,1,5,8723.0,1174.0,60.9,0,0,147.0,85,9,9,2,10.0,21.0,9.0,21.0,0,1,3,2,2,6,6,7,3,9,0.0,0,0,3,92.9,50.0,0,0,93908,4976,3000,6028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128410,NaN,NaN,10000,10000,9750.0,36 months,11.06%,327.68,B,B3,NaN,NaN,RENT,44400.0,Source Verified,Oct-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,980xx,WA,11.78,0,Oct-2008,2,40.0,NaN,15,0,6269,13.1%,25,f,5687.01,5544.84,5555.20,5416.32,4312.99,1242.21,0.0,0.0,0.0,Mar-2020,327.68,Apr-2020,Mar-2020,0,53.0,1,Individual,NaN,NaN,NaN,0,520,16440,3,1,1,1,2.0,10171,100.0,2,5,404,28.0,47700,0,3,5,6,1265.0,20037.0,2.3,0,0,61.0,119,1,1,0,1.0,NaN,1.0,40.0,1,2,4,6,8,3,14,22,4,15,0.0,0,0,3,92.0,0.0,0,0,57871,16440,20500,10171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128411,NaN,NaN,10000,10000,10000.0,36 months,16.91%,356.08,C,C5,Key Accounts Manager,2 years,RENT,80000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,other,Other,021xx,MA,17.72,1,Sep-2006,0,14.0,NaN,17,0,1942,30.8%,31,w,5899.34,5899.34,6043.97,6043.97,4100.66,1943.31,0.0,0.0,0.0,Mar-2020,356.08,Apr-2020,Mar-2020,0,25.0,1,Individual,NaN,NaN,NaN,0,0,59194,0,15,1,1,12.0,57252,85.0,0,0,1942,80.0,6300,0,5,0,1,3482.0,2058.0,48.5,0,0,144.0,142,40,12,0,131.0,30.0,NaN,30.0,3,1,1,1,5,22,2,9,1,17,0.0,0,0,1,74.2,0.0,0,0,73669,59194,4000,67369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df = df.drop(['url','member_id','id','desc'], axis=1)

df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,Apr-1995,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,828060,0,6,1,2,9.0,112027,29.0,4,8,19118,36.0,132400,3,2,5,11,34503.0,67341.0,46.0,0,0,173.0,284,8,8,3,8.0,NaN,0.0,NaN,0,11,11,13,20,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director of Sales,10+ years,MORTGAGE,72000.0,Source Verified,Dec-2018,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,Mar-2010,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,534,189279,0,1,0,1,18.0,22698,NaN,0,0,4056,47.0,24900,1,0,1,2,14560.0,8163.0,55.1,0,0,105.0,90,29,8,5,40.0,NaN,9.0,NaN,0,6,11,6,8,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,NaN,< 1 year,RENT,55000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,Apr-2007,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,21235,0,1,0,1,20.0,9376,76.0,0,3,3122,62.0,22000,1,0,0,4,2359.0,1119.0,89.3,0,0,140.0,140,13,13,0,13.0,NaN,15.0,44.0,0,4,7,4,5,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,Mar-1998,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,43351,1,2,1,1,10.0,28028,67.0,1,5,7533,53.0,29170,0,0,2,6,3096.0,4150.0,77.0,0,0,125.0,230,5,5,2,5.0,NaN,5.0,NaN,0,4,12,5,5,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion assistant,10+ years,MORTGAGE,56000.0,Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,Sep-2006,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,NaN,NaN,0,136,192983,0,2,0,2,14.0,66857,NaN,0,3,1608,29.0,15800,3,0,0,5,27569.0,7835.0,36.3,0,0,147.0,29,22,14,1,22.0,NaN,17.0,NaN,0,3,4,3,3,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
#first 10
df['int_rate'].head(10)

0     14.47%
1     22.35%
2     23.40%
3     18.94%
4     10.72%
5     11.31%
6     11.31%
7     11.80%
8     11.80%
9     18.94%
Name: int_rate, dtype: object

In [32]:
#specific value
df['int_rate'][0]

' 14.47%'

In [0]:
int_rate = " 15.25%"

In [36]:
#going to strip away the whitespace and % sign by 'Casting'
int_rate.strip().strip('%')
# still reading it as a str though.

'15.25'

In [38]:
float(int_rate.strip().strip("%"))
# now it reads  as a float.

15.25

In [0]:
# making a reusable piece of code that can be called
def int_rate_to_float(dirty_int_rate):
  return float(dirty_int_rate.strip().strip('%'))

In [40]:
#testing the piece of code
int_rate_to_float(' 15.47%')

15.47

In [41]:
type(int_rate_to_float(int_rate))

float

In [0]:
#
#
#
#
#

In [43]:
df['int_rate'].head()

0     14.47%
1     22.35%
2     23.40%
3     18.94%
4     10.72%
Name: int_rate, dtype: object

In [0]:
int_rates = [' 16.57%', ' 16.52%', ' 16.58%', ' 16.41%', ' 15.47%']

In [45]:
 clean_int_rates = []
 for int_rate in int_rates:
   clean_int_rates.append(int_rate_to_float(int_rate))

clean_int_rates

[16.57, 16.52, 16.58, 16.41, 15.47]

In [46]:
clean_int_rates = pd.Series(clean_int_rates)

clean_int_rates

0    16.57
1    16.52
2    16.58
3    16.41
4    15.47
dtype: float64

In [0]:
#
#
#
#
#

In [47]:
# The apply function applies a function to the df. cause logic.
df['int_rate_cleaned'] = df['int_rate'].apply(int_rate_to_float)

df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned
0,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,Apr-1995,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,828060,0,6,1,2,9.0,112027,29.0,4,8,19118,36.0,132400,3,2,5,11,34503.0,67341.0,46.0,0,0,173.0,284,8,8,3,8.0,NaN,0.0,NaN,0,11,11,13,20,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
1,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director of Sales,10+ years,MORTGAGE,72000.0,Source Verified,Dec-2018,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,Mar-2010,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,534,189279,0,1,0,1,18.0,22698,NaN,0,0,4056,47.0,24900,1,0,1,2,14560.0,8163.0,55.1,0,0,105.0,90,29,8,5,40.0,NaN,9.0,NaN,0,6,11,6,8,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,22.35
2,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,NaN,< 1 year,RENT,55000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,Apr-2007,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,21235,0,1,0,1,20.0,9376,76.0,0,3,3122,62.0,22000,1,0,0,4,2359.0,1119.0,89.3,0,0,140.0,140,13,13,0,13.0,NaN,15.0,44.0,0,4,7,4,5,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,23.40
3,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,Mar-1998,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,43351,1,2,1,1,10.0,28028,67.0,1,5,7533,53.0,29170,0,0,2,6,3096.0,4150.0,77.0,0,0,125.0,230,5,5,2,5.0,NaN,5.0,NaN,0,4,12,5,5,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,18.94
4,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion assistant,10+ years,MORTGAGE,56000.0,Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,Sep-2006,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,NaN,NaN,0,136,192983,0,2,0,2,14.0,66857,NaN,0,3,1608,29.0,15800,3,0,0,5,27569.0,7835.0,36.3,0,0,147.0,29,22,14,1,22.0,NaN,17.0,NaN,0,3,4,3,3,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72

In [48]:
df.dtypes.tail()

settlement_date           object
settlement_amount        float64
settlement_percentage    float64
settlement_term          float64
int_rate_cleaned         float64
dtype: object

In [49]:
#top 20 employment titles
df['emp_title'].value_counts(dropna=False).head(20)

NaN                   20947
Teacher                2090
Manager                1773
Registered Nurse        952
Driver                  924
RN                      726
Supervisor              697
Sales                   580
Project Manager         526
General Manager         523
Office Manager          521
Owner                   420
Director                402
Operations Manager      387
Truck Driver            387
Nurse                   326
Engineer                325
Sales Manager           304
manager                 301
Supervisor              270
Name: emp_title, dtype: int64

In [50]:
#there are ___ unique titles
df['emp_title'].nunique()

43892

In [51]:
len(df['emp_title'].value_counts())

43892

In [52]:
df['emp_title'].isnull().sum()

20947

In [0]:
import numpy as np

examples = ['owner','Supervisor',' Project Manager', np.NaN]

In [55]:
def clean_emp_title(title):
  if isinstance(title, str):
    return title.strip().title()
  else:
    return "Unknown"

for example in examples:
  print(clean_emp_title(example))

Owner
Supervisor
Project Manager
Unknown

In [56]:
[clean_emp_title(title) for title in examples]

['Owner', 'Supervisor', 'Project Manager', 'Unknown']

In [57]:
df['emp_title'].head(10)

0                        Staff Physician
1                      Director of Sales
2                                    NaN
3                          Receptionist
4                   Extrusion assistant
5                                Teacher
6                             Supervisor
7                                Analyst
8    Corporate Communications Strategist
9                        Project Manager
Name: emp_title, dtype: object

In [58]:
df['emp_title'].apply(clean_emp_title).head(10)

0                        Staff Physician
1                      Director Of Sales
2                                Unknown
3                           Receptionist
4                    Extrusion Assistant
5                                Teacher
6                             Supervisor
7                                Analyst
8    Corporate Communications Strategist
9                        Project Manager
Name: emp_title, dtype: object

In [59]:
df['emp_title'] = df['emp_title'].apply(clean_emp_title)

df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned
0,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,Apr-1995,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,828060,0,6,1,2,9.0,112027,29.0,4,8,19118,36.0,132400,3,2,5,11,34503.0,67341.0,46.0,0,0,173.0,284,8,8,3,8.0,NaN,0.0,NaN,0,11,11,13,20,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
1,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director Of Sales,10+ years,MORTGAGE,72000.0,Source Verified,Dec-2018,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,Mar-2010,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,534,189279,0,1,0,1,18.0,22698,NaN,0,0,4056,47.0,24900,1,0,1,2,14560.0,8163.0,55.1,0,0,105.0,90,29,8,5,40.0,NaN,9.0,NaN,0,6,11,6,8,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,22.35
2,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,Unknown,< 1 year,RENT,55000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,Apr-2007,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,21235,0,1,0,1,20.0,9376,76.0,0,3,3122,62.0,22000,1,0,0,4,2359.0,1119.0,89.3,0,0,140.0,140,13,13,0,13.0,NaN,15.0,44.0,0,4,7,4,5,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,23.40
3,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,Mar-1998,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,43351,1,2,1,1,10.0,28028,67.0,1,5,7533,53.0,29170,0,0,2,6,3096.0,4150.0,77.0,0,0,125.0,230,5,5,2,5.0,NaN,5.0,NaN,0,4,12,5,5,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,18.94
4,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion Assistant,10+ years,MORTGAGE,56000.0,Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,Sep-2006,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,NaN,NaN,0,136,192983,0,2,0,2,14.0,66857,NaN,0,3,1608,29.0,15800,3,0,0,5,27569.0,7835.0,36.3,0,0,147.0,29,22,14,1,22.0,NaN,17.0,NaN,0,3,4,3,3,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72

In [60]:
df['emp_title'].value_counts().head(20)

Unknown               20947
Teacher                2557
Manager                2395
Registered Nurse       1418
Driver                 1258
Supervisor             1160
Truck Driver            920
Rn                      834
Office Manager          805
Sales                   803
General Manager         791
Project Manager         720
Owner                   625
Director                523
Operations Manager      518
Sales Manager           500
Police Officer          440
Nurse                   425
Technician              420
Engineer                412
Name: emp_title, dtype: int64

In [61]:
df['emp_title'].nunique()

34902

In [62]:
df['emp_title'].isnull().sum()

0

In [0]:
#
#
#
#
#

In [64]:
[col for col in df if col.endswith('_d')]

['issue_d', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d']

In [65]:
df['issue_d'].head()

0    Dec-2018
1    Dec-2018
2    Dec-2018
3    Dec-2018
4    Dec-2018
Name: issue_d, dtype: object

In [66]:
df['issue_d'].value_counts()

Oct-2018    46305
Nov-2018    41973
Dec-2018    40134
Name: issue_d, dtype: int64

In [0]:
df['issue_d'] = pd.to_datetime(df['issue_d'], infer_datetime_format=True)

In [68]:
df['issue_d'].head()

0   2018-12-01
1   2018-12-01
2   2018-12-01
3   2018-12-01
4   2018-12-01
Name: issue_d, dtype: datetime64[ns]

In [69]:
df['issue_d'][0]

Timestamp('2018-12-01 00:00:00')

In [70]:
df.dtypes[:15]

loan_amnt                       int64
funded_amnt                     int64
funded_amnt_inv               float64
term                           object
int_rate                       object
installment                   float64
grade                          object
sub_grade                      object
emp_title                      object
emp_length                     object
home_ownership                 object
annual_inc                    float64
verification_status            object
issue_d                datetime64[ns]
loan_status                    object
dtype: object

In [71]:
df['issue_d'].dt.year

0         2018
1         2018
2         2018
3         2018
4         2018
          ...
128407    2018
128408    2018
128409    2018
128410    2018
128411    2018
Name: issue_d, Length: 128412, dtype: int64

In [72]:
df['issue_d'].dt.month

0         12
1         12
2         12
3         12
4         12
          ..
128407    10
128408    10
128409    10
128410    10
128411    10
Name: issue_d, Length: 128412, dtype: int64

In [73]:
df['issue_year'] = df['issue_d'].dt.year
df['issue_month'] = df['issue_d'].dt.month

df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned,issue_year,issue_month
0,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,2018-12-01,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,Apr-1995,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,828060,0,6,1,2,9.0,112027,29.0,4,8,19118,36.0,132400,3,2,5,11,34503.0,67341.0,46.0,0,0,173.0,284,8,8,3,8.0,NaN,0.0,NaN,0,11,11,13,20,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47,2018,12
1,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director Of Sales,10+ years,MORTGAGE,72000.0,Source Verified,2018-12-01,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,Mar-2010,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,534,189279,0,1,0,1,18.0,22698,NaN,0,0,4056,47.0,24900,1,0,1,2,14560.0,8163.0,55.1,0,0,105.0,90,29,8,5,40.0,NaN,9.0,NaN,0,6,11,6,8,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,22.35,2018,12
2,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,Unknown,< 1 year,RENT,55000.0,Source Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,Apr-2007,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,21235,0,1,0,1,20.0,9376,76.0,0,3,3122,62.0,22000,1,0,0,4,2359.0,1119.0,89.3,0,0,140.0,140,13,13,0,13.0,NaN,15.0,44.0,0,4,7,4,5,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,23.40,2018,12
3,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,Mar-1998,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,43351,1,2,1,1,10.0,28028,67.0,1,5,7533,53.0,29170,0,0,2,6,3096.0,4150.0,77.0,0,0,125.0,230,5,5,2,5.0,NaN,5.0,NaN,0,4,12,5,5,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,18.94,2018,12
4,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion Assistant,10+ years,MORTGAGE,56000.0,Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,Sep-2006,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,NaN,NaN,0,136,192983,0,2,0,2,14.0,66857,NaN,0,3,1608,29.0,15800,3,0,0,5,27569.0,7835.0,36.3,0,0,147.0,29,22,14,1,22.0,NaN,17.0,NaN,0,3,4,3,3,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72,2018,12

In [74]:
df.dtypes[-5:]

settlement_percentage    float64
settlement_term          float64
int_rate_cleaned         float64
issue_year                 int64
issue_month                int64
dtype: object

In [0]:
df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], infer_datetime_format=True)

In [76]:
df['earliest_cr_line'].head()

0   1995-04-01
1   2010-03-01
2   2007-04-01
3   1998-03-01
4   2006-09-01
Name: earliest_cr_line, dtype: datetime64[ns]

In [77]:
(df['issue_d'] - df['earliest_cr_line']).dt.days

0          8645
1          3197
2          4262
3          7580
4          4474
          ...
128407    12114
128408    13241
128409     4505
128410     3652
128411     4413
Length: 128412, dtype: int64

In [78]:
df['years_from_earliest_credit_to_issue'] = (df['issue_d'] - df['earliest_cr_line']).dt.days / 365

df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned,issue_year,issue_month,years_from_earliest_credit_to_issue
0,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,2018-12-01,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,1995-04-01,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,828060,0,6,1,2,9.0,112027,29.0,4,8,19118,36.0,132400,3,2,5,11,34503.0,67341.0,46.0,0,0,173.0,284,8,8,3,8.0,NaN,0.0,NaN,0,11,11,13,20,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47,2018,12,23.684932
1,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director Of Sales,10+ years,MORTGAGE,72000.0,Source Verified,2018-12-01,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,2010-03-01,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,534,189279,0,1,0,1,18.0,22698,NaN,0,0,4056,47.0,24900,1,0,1,2,14560.0,8163.0,55.1,0,0,105.0,90,29,8,5,40.0,NaN,9.0,NaN,0,6,11,6,8,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,22.35,2018,12,8.758904
2,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,Unknown,< 1 year,RENT,55000.0,Source Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,2007-04-01,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,21235,0,1,0,1,20.0,9376,76.0,0,3,3122,62.0,22000,1,0,0,4,2359.0,1119.0,89.3,0,0,140.0,140,13,13,0,13.0,NaN,15.0,44.0,0,4,7,4,5,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,23.40,2018,12,11.676712
3,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,1998-03-01,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,43351,1,2,1,1,10.0,28028,67.0,1,5,7533,53.0,29170,0,0,2,6,3096.0,4150.0,77.0,0,0,125.0,230,5,5,2,5.0,NaN,5.0,NaN,0,4,12,5,5,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,18.94,2018,12,20.767123
4,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion Assistant,10+ years,MORTGAGE,56000.0,Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,2006-09-01,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,NaN,NaN,0,136,192983,0,2,0,2,14.0,66857,NaN,0,3,1608,29.0,15800,3,0,0,5,27569.0,7835.0,36.3,0,0,147.0,29,22,14,1,22.0,NaN,17.0,NaN,0,3,4,3,3,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72,2018,12,12.257534

In [79]:
df['years_from_earliest_credit_to_issue'].describe()

count    128412.000000
mean         16.054497
std           7.908317
min           3.084932
25%          11.093151
50%          14.427397
75%          19.846575
max          68.961644
Name: years_from_earliest_credit_to_issue, dtype: float64

Convert the term column from string to integer.

Make a column named loan_status_is_great. It should contain the integer 1 if loan_status is "Current" or "Fully Paid." Else it should contain the integer 0.

Make last_pymnt_d_month and last_pymnt_d_year columns.

In [80]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned,issue_year,issue_month,years_from_earliest_credit_to_issue
0,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,2018-12-01,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,1995-04-01,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,828060,0,6,1,2,9.0,112027,29.0,4,8,19118,36.0,132400,3,2,5,11,34503.0,67341.0,46.0,0,0,173.0,284,8,8,3,8.0,NaN,0.0,NaN,0,11,11,13,20,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47,2018,12,23.684932
1,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director Of Sales,10+ years,MORTGAGE,72000.0,Source Verified,2018-12-01,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,2010-03-01,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,534,189279,0,1,0,1,18.0,22698,NaN,0,0,4056,47.0,24900,1,0,1,2,14560.0,8163.0,55.1,0,0,105.0,90,29,8,5,40.0,NaN,9.0,NaN,0,6,11,6,8,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,22.35,2018,12,8.758904
2,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,Unknown,< 1 year,RENT,55000.0,Source Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,2007-04-01,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,21235,0,1,0,1,20.0,9376,76.0,0,3,3122,62.0,22000,1,0,0,4,2359.0,1119.0,89.3,0,0,140.0,140,13,13,0,13.0,NaN,15.0,44.0,0,4,7,4,5,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,23.40,2018,12,11.676712
3,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,1998-03-01,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,43351,1,2,1,1,10.0,28028,67.0,1,5,7533,53.0,29170,0,0,2,6,3096.0,4150.0,77.0,0,0,125.0,230,5,5,2,5.0,NaN,5.0,NaN,0,4,12,5,5,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,18.94,2018,12,20.767123
4,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion Assistant,10+ years,MORTGAGE,56000.0,Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,2006-09-01,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,NaN,NaN,0,136,192983,0,2,0,2,14.0,66857,NaN,0,3,1608,29.0,15800,3,0,0,5,27569.0,7835.0,36.3,0,0,147.0,29,22,14,1,22.0,NaN,17.0,NaN,0,3,4,3,3,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72,2018,12,12.257534

In [81]:
df['term']

0          36 months
1          36 months
2          60 months
3          36 months
4          36 months
             ...
128407     36 months
128408     36 months
128409     36 months
128410     36 months
128411     36 months
Name: term, Length: 128412, dtype: object

In [82]:
df['term'][0]

' 36 months'

In [0]:
term_example = " 36 months"

In [85]:
term_example.strip('months').strip()

'36'

In [86]:
int(term_example.strip('months').strip())

36

In [0]:
def term_str_to_int(dirty_term_rate):
  return int(dirty_term_rate.strip('months').strip())

In [0]:
term_rates = ['  36 months','  60 months','  36 months','  60 months']

In [99]:
term_str_to_int(term_example)

36

In [102]:
proper_terms=[]
for str_term in term_rates:
  proper_terms.append(term_str_to_int(str_term))

proper_terms = pd.Series(proper_terms)

proper_terms

0    36
1    60
2    36
3    60
dtype: int64

In [103]:
df['term'] = df['term'].apply(term_str_to_int)

df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned,issue_year,issue_month,years_from_earliest_credit_to_issue
0,35000,35000,35000.0,36,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,2018-12-01,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,1995-04-01,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,828060,0,6,1,2,9.0,112027,29.0,4,8,19118,36.0,132400,3,2,5,11,34503.0,67341.0,46.0,0,0,173.0,284,8,8,3,8.0,NaN,0.0,NaN,0,11,11,13,20,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47,2018,12,23.684932
1,5000,5000,5000.0,36,22.35%,191.86,D,D5,Director Of Sales,10+ years,MORTGAGE,72000.0,Source Verified,2018-12-01,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,2010-03-01,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,534,189279,0,1,0,1,18.0,22698,NaN,0,0,4056,47.0,24900,1,0,1,2,14560.0,8163.0,55.1,0,0,105.0,90,29,8,5,40.0,NaN,9.0,NaN,0,6,11,6,8,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,22.35,2018,12,8.758904
2,10000,10000,10000.0,60,23.40%,284.21,E,E1,Unknown,< 1 year,RENT,55000.0,Source Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,2007-04-01,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,21235,0,1,0,1,20.0,9376,76.0,0,3,3122,62.0,22000,1,0,0,4,2359.0,1119.0,89.3,0,0,140.0,140,13,13,0,13.0,NaN,15.0,44.0,0,4,7,4,5,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,23.40,2018,12,11.676712
3,17100,17100,17100.0,36,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,1998-03-01,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,43351,1,2,1,1,10.0,28028,67.0,1,5,7533,53.0,29170,0,0,2,6,3096.0,4150.0,77.0,0,0,125.0,230,5,5,2,5.0,NaN,5.0,NaN,0,4,12,5,5,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,18.94,2018,12,20.767123
4,4000,4000,4000.0,36,10.72%,130.43,B,B2,Extrusion Assistant,10+ years,MORTGAGE,56000.0,Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,2006-09-01,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,NaN,NaN,0,136,192983,0,2,0,2,14.0,66857,NaN,0,3,1608,29.0,15800,3,0,0,5,27569.0,7835.0,36.3,0,0,147.0,29,22,14,1,22.0,NaN,17.0,NaN,0,3,4,3,3,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72,2018,12,12.257534

Make a column named loan_status_is_great. It should contain the integer 1 if loan_status is "Current" or "Fully Paid." Else it should contain the integer 0.

Make last_pymnt_d_month and last_pymnt_d_year columns.

In [105]:
df['loan_status']

0          Fully Paid
1          Fully Paid
2             Current
3             Current
4             Current
             ...
128407    Charged Off
128408        Current
128409        Current
128410        Current
128411        Current
Name: loan_status, Length: 128412, dtype: object

In [106]:
df['loan_status'].value_counts(dropna=False).head(20)

Current               89058
Fully Paid            26966
Charged Off            7668
Late (31-120 days)     2206
In Grace Period        1844
Late (16-30 days)       609
Default                  61
Name: loan_status, dtype: int64

In [0]:
loanexamples = ['Current','Fully Paid','Charged Off','Late (31-120 days)']

In [114]:
def int_loan(loan):
  if loan=='Current' or loan=='Fully Paid':
    return 1
  else:
    return 0

for lexample in loanexamples:
  print(int_loan(lexample))

1
1
0
0

In [128]:
[int_loan(loan) for loan in loanexamples]

[1, 1, 0, 0]

In [132]:
df['loan_status_is_great'] = df['loan_status'].apply(int_loan)

df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned,issue_year,issue_month,years_from_earliest_credit_to_issue,loan_status_is_great
0,35000,35000,35000.0,36,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,2018-12-01,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,1995-04-01,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,828060,0,6,1,2,9.0,112027,29.0,4,8,19118,36.0,132400,3,2,5,11,34503.0,67341.0,46.0,0,0,173.0,284,8,8,3,8.0,NaN,0.0,NaN,0,11,11,13,20,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47,2018,12,23.684932,1
1,5000,5000,5000.0,36,22.35%,191.86,D,D5,Director Of Sales,10+ years,MORTGAGE,72000.0,Source Verified,2018-12-01,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,2010-03-01,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,534,189279,0,1,0,1,18.0,22698,NaN,0,0,4056,47.0,24900,1,0,1,2,14560.0,8163.0,55.1,0,0,105.0,90,29,8,5,40.0,NaN,9.0,NaN,0,6,11,6,8,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,22.35,2018,12,8.758904,1
2,10000,10000,10000.0,60,23.40%,284.21,E,E1,Unknown,< 1 year,RENT,55000.0,Source Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,2007-04-01,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,21235,0,1,0,1,20.0,9376,76.0,0,3,3122,62.0,22000,1,0,0,4,2359.0,1119.0,89.3,0,0,140.0,140,13,13,0,13.0,NaN,15.0,44.0,0,4,7,4,5,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,23.40,2018,12,11.676712,1
3,17100,17100,17100.0,36,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,2018-12-01,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,1998-03-01,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,43351,1,2,1,1,10.0,28028,67.0,1,5,7533,53.0,29170,0,0,2,6,3096.0,4150.0,77.0,0,0,125.0,230,5,5,2,5.0,NaN,5.0,NaN,0,4,12,5,5,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,18.94,2018,12,20.767123,1
4,4000,4000,4000.0,36,10.72%,130.43,B,B2,Extrusion Assistant,10+ years,MORTGAGE,56000.0,Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,2006-09-01,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,NaN,NaN,0,136,192983,0,2,0,2,14.0,66857,NaN,0,3,1608,29.0,15800,3,0,0,5,27569.0,7835.0,36.3,0,0,147.0,29,22,14,1,22.0,NaN,17.0,NaN,0,3,4,3,3,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72,2018,12,12.257534,1

Make last_pymnt_d_month and last_pymnt_d_year columns.

In [133]:
[col for col in df if col.endswith('_d')]

['issue_d', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d']

In [134]:
df['last_pymnt_d'].head()

0    Aug-2019
1    Jul-2019
2    Mar-2020
3    Mar-2020
4    Mar-2020
Name: last_pymnt_d, dtype: object

In [144]:
df['last_pymnt_d'].value_counts(dropna=False)

2020-03-01    91525
2020-02-01     3230
2019-07-01     3146
2019-12-01     2763
2019-09-01     2755
2019-10-01     2722
2019-08-01     2716
2019-05-01     2547
2019-11-01     2394
2020-01-01     2384
2019-04-01     2356
2019-06-01     2288
2019-03-01     1984
2019-02-01     1915
2019-01-01     1561
2018-12-01     1054
2018-11-01      679
2018-10-01      234
NaT             159
Name: last_pymnt_d, dtype: int64

In [135]:
df['last_pymnt_d'].value_counts()

Mar-2020    91525
Feb-2020     3230
Jul-2019     3146
Dec-2019     2763
Sep-2019     2755
Oct-2019     2722
Aug-2019     2716
May-2019     2547
Nov-2019     2394
Jan-2020     2384
Apr-2019     2356
Jun-2019     2288
Mar-2019     1984
Feb-2019     1915
Jan-2019     1561
Dec-2018     1054
Nov-2018      679
Oct-2018      234
Name: last_pymnt_d, dtype: int64

In [145]:
df.dtypes

loan_amnt                                              int64
funded_amnt                                            int64
funded_amnt_inv                                      float64
term                                                   int64
int_rate                                              object
installment                                          float64
grade                                                 object
sub_grade                                             object
emp_title                                             object
emp_length                                            object
home_ownership                                        object
annual_inc                                           float64
verification_status                                   object
issue_d                                       datetime64[ns]
loan_status                                           object
pymnt_plan                                            object
purpose                                               object
title                                                 object
zip_code                                              object
addr_state                                            object
dti                                                  float64
delinq_2yrs                                            int64
earliest_cr_line                              datetime64[ns]
inq_last_6mths                                         int64
mths_since_last_delinq                               float64
mths_since_last_record                               float64
open_acc                                               int64
pub_rec                                                int64
revol_bal                                              int64
revol_util                                            object
total_acc                                              int64
initial_list_status                                   object
out_prncp                                            float64
out_prncp_inv                                        float64
total_pymnt                                          float64
total_pymnt_inv                                      float64
total_rec_prncp                                      float64
total_rec_int                                        float64
total_rec_late_fee                                   float64
recoveries                                           float64
collection_recovery_fee                              float64
last_pymnt_d                                  datetime64[ns]
last_pymnt_amnt                                      float64
next_pymnt_d                                          object
last_credit_pull_d                                    object
collections_12_mths_ex_med                             int64
mths_since_last_major_derog                          float64
policy_code                                            int64
application_type                                      object
annual_inc_joint                                     float64
dti_joint                                            float64
verification_status_joint                             object
acc_now_delinq                                         int64
tot_coll_amt                                           int64
tot_cur_bal                                            int64
open_acc_6m                                            int64
open_act_il                                            int64
open_il_12m                                            int64
open_il_24m                                            int64
mths_since_rcnt_il                                   float64
total_bal_il                                           int64
il_util                                              float64
open_rv_12m                                            int64
open_rv_24m                                            int64
max_bal_bc                                             int64
all_util                                             float64
total_rev_hi_lim                                       int64
inq_fi                                                 int64
total_cu_tl                                            int64
inq_last_12m                                           int64
acc_open_past_24mths                                   int64
avg_cur_bal                                          float64
bc_open_to_buy                                       float64
bc_util                                              float64
chargeoff_within_12_mths                               int64
delinq_amnt                                            int64
mo_sin_old_il_acct                                   float64
mo_sin_old_rev_tl_op                                   int64
mo_sin_rcnt_rev_tl_op                                  int64
mo_sin_rcnt_tl                                         int64
mort_acc                                               int64
mths_since_recent_bc                                 float64
mths_since_recent_bc_dlq                             float64
mths_since_recent_inq                                float64
mths_since_recent_revol_delinq                       float64
num_accts_ever_120_pd                                  int64
num_actv_bc_tl                                         int64
num_actv_rev_tl                                        int64
num_bc_sats                                            int64
num_bc_tl                                              int64
num_il_tl                                              int64
num_op_rev_tl                                          int64
num_rev_accts                                          int64
num_rev_tl_bal_gt_0                                    int64
num_sats                                               int64
num_tl_120dpd_2m                                     float64
num_tl_30dpd                                           int64
num_tl_90g_dpd_24m                                     int64
num_tl_op_past_12m                                     int64
pct_tl_nvr_dlq                                       float64
percent_bc_gt_75                                     float64
pub_rec_bankruptcies                                   int64
tax_liens                                              int64
tot_hi_cred_lim                                        int64
total_bal_ex_mort                                      int64
total_bc_limit                                         int64
total_il_high_credit_limit                             int64
revol_bal_joint                                      float64
sec_app_earliest_cr_line                              object
sec_app_inq_last_6mths                               float64
sec_app_mort_acc                                     float64
sec_app_open_acc                                     float64
sec_app_revol_util                                   float64
sec_app_open_act_il                                  float64
sec_app_num_rev_accts                                float64
sec_app_chargeoff_within_12_mths                     float64
sec_app_collections_12_mths_ex_med                   float64
sec_app_mths_since_last_major_derog                  float64
hardship_flag                                         object
hardship_type                                         object
hardship_reason                                       object
hardship_status                                       object
deferral_term                                        float64
hardship_amount                                      float64
hardship_start_date                                   object
hardship_end_date                                     object
payment_plan_start_date                               object
hardship_length                                      float64
hardship_dpd                                         float64
hardship_loan_status                                  object
orig_projected_additional_accrued_interest           float64
hardship_payoff_balance_amount                       float64
hardship_last_payment_amount                         float64
debt_settlement_flag                                  object
debt_settlement_flag_date                             object
settlement_status                                     object
settlement_date                                       object
settlement_amount                                    float64
settlement_percentage                                float64
settlement_term                                      float64
int_rate_cleaned                                     float64
issue_year                                             int64
issue_month                                            int64
years_from_earliest_credit_to_issue                  float64
loan_status_is_great                                   int64
dtype: object

In [0]:
df['last_pymnt_d'] = pd.to_datetime(df['last_pymnt_d'], infer_datetime_format=True)

In [138]:
df['last_pymnt_d'].head()

0   2019-08-01
1   2019-07-01
2   2020-03-01
3   2020-03-01
4   2020-03-01
Name: last_pymnt_d, dtype: datetime64[ns]

In [143]:
df['last_pymnt_d'][0]

Timestamp('2019-08-01 00:00:00')

In [156]:
df['last_pymnt_d_month'] = df['last_pymnt_d'].dt.month
df['last_pymnt_d_year'] = df['last_pymnt_d'].dt.year

df.tail(150)

        loan_amnt  funded_amnt  funded_amnt_inv  term int_rate  installment  \
128262      20000        20000     20000.000000    36    8.46%       630.99
128263      31675        31675     31650.000000    36   26.31%      1281.45
128264      22925        22925     22900.000000    60   25.34%       677.46
128265      15000        15000     15000.000000    36    6.11%       457.08
128266      40000        40000     40000.000000    36    7.84%      1250.51
128267      24000        24000     24000.000000    60   15.02%       571.22
128268      21500        21500     21475.000000    36   19.92%       798.15
128269       3000         3000      3000.000000    36   17.97%       108.42
128270      12000        12000     12000.000000    60    6.67%       235.76
128271      13225        13225     13225.000000    36   14.47%       455.03
128272      40000        40000     40000.000000    60   14.47%       940.51
128273      15000        15000     15000.000000    36   18.94%       549.39
128274       5000         5000      5000.000000    36   13.56%       169.83
128275      30000        30000     29975.000000    36    6.11%       914.16
128276      15000        15000     15000.000000    36    8.46%       473.24
128277      15000        15000     15000.000000    36   18.94%       549.39
128278      14000        14000     14000.000000    36   13.56%       475.51
128279       6000         6000      6000.000000    36    7.21%       185.84
128280      40000        40000     39975.000000    36    6.67%      1229.06
128281      15000        15000     15000.000000    36   11.06%       491.51
128282      10500        10500     10500.000000    60   27.27%       322.32
128283       5000         5000      5000.000000    36   10.08%       161.53
128284      40000        40000     39975.000000    36    7.84%      1250.51
128285       3000         3000      3000.000000    36   15.02%       104.03
128286      15000        15000     15000.000000    36   11.06%       491.51
128287       5000         5000      5000.000000    36    7.21%       154.87
128288      10000        10000     10000.000000    36   14.47%       344.07
128289      11000        11000     11000.000000    36    7.21%       340.71
128290      10800        10800     10800.000000    36    7.21%       334.52
128291      10000        10000     10000.000000    36    7.84%       312.63
128292      13000        13000     12975.000000    36   17.97%       469.79
128293      40000        40000     40000.000000    60   15.02%       952.02
128294      25000        25000     25000.000000    36    6.11%       761.80
128295      30875        30875     30875.000000    60   25.34%       912.39
128296      16000        16000     15975.000000    36   16.14%       563.62
128297      15000        15000     15000.000000    36   23.40%       583.78
128298      12500        12500     12500.000000    60   10.47%       268.49
128299       5000         5000      5000.000000    36   12.73%       167.83
128300      20000        20000     20000.000000    60   22.35%       556.37
128301      12325        12325     12275.000000    36   17.97%       445.40
128302      12000        12000     12000.000000    60   15.02%       285.61
128303      29000        29000     28975.000000    36    6.11%       883.69
128304      30000        30000     29975.000000    60    6.67%       589.38
128305      40000        40000     39975.000000    36    6.11%      1218.88
128306      25475        25475     25425.000000    36   22.35%       977.53
128307       6000         6000      6000.000000    36    8.46%       189.30
128308      20000        20000     19975.000000    36   16.91%       712.16
128309      35000        35000     34975.000000    36   13.56%      1188.76
128310      32000        32000     32000.000000    36    7.84%      1000.41
128311      34000        34000     33998.738091    36    6.67%      1044.70
128312      40000        40000     40000.000000    36    6.11%      1218.88
128313      25000        25000     24950.000000    36   22.35%       959.30
128314      12000        12000     12000.000000    36   15.02%       416.11
128315      10000        10000     10000.000000    36   15.02%       346.76
128316      35000        35000     34950.000000    36   24.37%      1379.96
128317      23000        23000     23000.000000    36   10.08%       743.01
128318      15500        15500     15500.000000    36    7.84%       484.58
128319      30000        30000     29975.000000    60   27.27%       920.91
128320      17400        17400     17125.000000    36   11.55%       574.20
128321      35000        35000     34975.000000    36   14.47%      1204.23
128322      12000        12000     12000.000000    60   22.35%       333.82
128323      18000        18000     18000.000000    60    7.84%       363.60
128324      27000        27000     27000.000000    36    6.11%       822.74
128325      16000        16000     16000.000000    60   10.08%       340.59
128326      10000        10000     10000.000000    36   16.14%       352.27
128327      10000        10000     10000.000000    36    6.11%       304.72
128328      28000        28000     27950.000000    36   17.97%      1011.85
128329       1000         1000      1000.000000    36   23.40%        38.92
128330      19200        19200     19199.516656    60   20.89%       518.24
128331      25000        25000     25000.000000    60   13.56%       576.02
128332       7000         7000      7000.000000    36    6.11%       213.31
128333      12000        12000     12000.000000    36   15.02%       416.11
128334      20000        20000     20000.000000    36    7.84%       625.26
128335      10000        10000     10000.000000    36    7.21%       309.74
128336      19000        19000     19000.000000    60    7.84%       383.80
128337       4000         4000      4000.000000    36   18.94%       146.51
128338       4950         4950      4938.256254    36   11.55%       163.35
128339      27000        27000     27000.000000    36    7.21%       836.28
128340      27000        27000     26975.000000    36   24.37%      1064.54
128341      10000        10000     10000.000000    60   19.92%       264.50
128342      20000        20000     20000.000000    36   14.47%       688.13
128343      22000        22000     22000.000000    36   24.37%       867.41
128344      11000        11000     11000.000000    60   12.73%       248.77
128345      30000        30000     29975.000000    36    7.21%       929.20
128346      31400        31400     31400.000000    60    7.84%       634.28
128347      35000        35000     35000.000000    36    7.84%      1094.20
128348      40000        40000     39975.000000    60    7.84%       808.00
128349      30000        30000     30000.000000    36   15.02%      1040.26
128350      12000        12000     12000.000000    60    6.11%       232.61
128351      20000        20000     20000.000000    36   13.56%       679.29
128352      18000        18000     18000.000000    36    7.21%       557.52
128353      29125        29125     29075.000000    36   27.27%      1193.26
128354      20000        20000     20000.000000    36   10.08%       646.10
128355      10000        10000     10000.000000    36   11.55%       330.00
128356       9000         9000      9000.000000    36   11.55%       297.00
128357      25000        25000     25000.000000    36   27.27%      1024.26
128358       7500         7500      7500.000000    36   16.91%       267.06
128359      25000        25000     24975.000000    36   27.27%      1024.26
128360      32000        32000     31975.000000    36    7.21%       991.15
128361      40000        40000     40000.000000    60   11.55%       880.71
128362      15000        15000     15000.000000    36   11.06%       491.51
128363      10000        10000     10000.000000    36   11.06%       327.68
128364      22800        22800     22800.000000    60   17.97%       578.60
128365      15500        15500     15500.000000    36    8.46%       489.01
128366      35000        35000     35000.000000    36   13.56%      1188.76
128367       9500         9500      9500.000000    36   14.47%       326.87
128368      35000        35000     35000.000000    60   17.97%       888.20
128369       8000         8000      8000.000000    36   14.47%       275.26
128370      40000        40000     40000.000000    60    7.84%       808.00
128371      12800        12800     12800.000000    36    8.46%       403.83
128372       5500         5500      5500.000000    36    7.84%       171.95
128373      40000        40000     39975.000000    36    6.11%      1218.88
128374      20275        20275     20275.000000    60   22.35%       564.02
128375       1500         1500      1500.000000    36   11.55%        49.50
128376      17500        17500     17500.000000    36   13.56%       594.38
128377      40000        40000     40000.000000    60    6.67%       785.84
128378      18000        18000     18000.000000    60   27.27%       552.55
128379      35000        35000     35000.000000    36   11.06%      1146.85
128380      15000        15000     15000.000000    60   16.91%       372.07
128381       8000         8000      8000.000000    36    7.84%       250.11
128382       8000         8000      8000.000000    36   16.91%       284.87
128383      10000        10000     10000.000000    36   17.97%       361.38
128384       6000         6000      6000.000000    36   11.55%       198.00
128385      25000        25000     25000.000000    60   26.31%       753.11
128386      24000        24000     24000.000000    36   13.56%       815.15
128387      17000        17000     17000.000000    60   17.97%       431.42
128388      20000        20000     20000.000000    36    8.46%       630.99
128389      35000        35000     34975.000000    36    6.67%      1075.43
128390       6500         6500      6500.000000    36   16.91%       231.46
128391       6000         6000      5750.000000    36   11.55%       198.00
128392      24000        24000     24000.000000    36   19.92%       890.95
128393       6500         6500      6500.000000    36   26.31%       262.97
128394       5000         5000      5000.000000    36    6.11%       152.36
128395      22000        22000     22000.000000    36   11.55%       726.00
128396      24000        24000     24000.000000    60   15.02%       571.22
128397      20000        20000     20000.000000    60   15.02%       476.01
128398      12000        12000     12000.000000    60   18.94%       310.90
128399       5000         5000      5000.000000    36   15.02%       173.38
128400      20000        20000     20000.000000    60   15.02%       476.01
128401       5000         5000      5000.000000    36   16.14%       176.14
128402      17500        17500     17500.000000    60   22.35%       486.82
128403      20000        20000     20000.000000    36   11.55%       660.00
128404      22000        22000     22000.000000    60    7.84%       444.40
128405       5000         5000      5000.000000    36   16.14%       176.14
128406       5600         5600      5600.000000    36   13.56%       190.21
128407      23000        23000     23000.000000    36   15.02%       797.53
128408      10000        10000     10000.000000    36   15.02%       346.76
128409       5000         5000      5000.000000    36   13.56%       169.83
128410      10000        10000      9750.000000    36   11.06%       327.68
128411      10000        10000     10000.000000    36   16.91%       356.08

       grade sub_grade                               emp_title emp_length  \
128262     A        A5                               Professor     1 year
128263     E        E4                                 Unknown        NaN
128264     E        E3          Sales Manager/Used Car Manager    5 years
128265     A        A1                              Specialist    5 years
128266     A        A4                       Campus Supervisor    4 years
128267     C        C3                               Paralegal  10+ years
128268     D        D3                                Ap Clerk    2 years
128269     D        D1                                 Unknown        NaN
128270     A        A2                  Insurance Under Writer    2 years
128271     C        C2                          Budget Manager  10+ years
128272     C        C2                        Retail Associate  10+ years
128273     D        D2                     Hr Business Partner    2 years
128274     C        C1                              Data Clerk  10+ years
128275     A        A1                            Vp, Of Sales    3 years
128276     A        A5                                 Unknown        NaN
128277     D        D2                          Home Caregiver    3 years
128278     C        C1                      Casino Table Games    4 years
128279     A        A3                             Coordinator    6 years
128280     A        A2                                 Unknown   < 1 year
128281     B        B3                              Bookkeeper    2 years
128282     E        E5                              Rsr Driver    3 years
128283     B        B1                Financial Administration  10+ years
128284     A        A4      Senior Manager Of Audio Production    4 years
128285     C        C3                        Paint Technician  10+ years
128286     B        B3                                 Unknown        NaN
128287     A        A3                                 Unknown        NaN
128288     C        C2                                 Unknown        NaN
128289     A        A3                                 Unknown        NaN
128290     A        A3                    Retail Store Manager    8 years
128291     A        A4                               Bartender  10+ years
128292     D        D1                          Office Manager    7 years
128293     C        C3                         Service Advisor    2 years
128294     A        A1                     Solutions Architect     1 year
128295     E        E3                                 Teacher  10+ years
128296     C        C4                  Contact Representative    2 years
128297     E        E1          Associate Director Of Catering    2 years
128298     B        B2                      Automation Analyst    8 years
128299     B        B5                Administrative Assistant  10+ years
128300     D        D5                      Operations Manager  10+ years
128301     D        D1                        Dental Hygienist    6 years
128302     C        C3                Public Health Specialist    8 years
128303     A        A1       Principal Application Architect I    2 years
128304     A        A2                            Line Manager  10+ years
128305     A        A1                Corporate Vice President  10+ years
128306     D        D5                       Software Engineer    3 years
128307     A        A5                                 Unknown        NaN
128308     C        C5                          Client Partner  10+ years
128309     C        C1                 Materials Launch Manage  10+ years
128310     A        A4  Contractor (It & Software Development)    3 years
128311     A        A2            Regional Performance Manager  10+ years
128312     A        A1                      Director Workplace    2 years
128313     D        D5                  Infrastruture Engineer   < 1 year
128314     C        C3      Medical Records Billing Specialist    6 years
128315     C        C3                             Food Server    3 years
128316     E        E2                            Area Manager     1 year
128317     B        B1                                 Unknown   < 1 year
128318     A        A4                       Postal Supervisor  10+ years
128319     E        E5                                 Plumber   < 1 year
128320     B        B4                      Service Technician    6 years
128321     C        C2                          Superintendant   < 1 year
128322     D        D5                   Customer Service Lead  10+ years
128323     A        A4                       Assistant Manager    5 years
128324     A        A1                      Operations Manager    4 years
128325     B        B1                                Director   < 1 year
128326     C        C4                        Flight Attendant    8 years
128327     A        A1                        Practice Manager  10+ years
128328     D        D1                           Federal Agent  10+ years
128329     E        E1                                 Unknown        NaN
128330     D        D4                     Subrogation Analyst  10+ years
128331     C        C1                          Operations Nco  10+ years
128332     A        A1                Administrative Typist Ii    2 years
128333     C        C3                        Registered Nurse  10+ years
128334     A        A4                                 Unknown   < 1 year
128335     A        A3                       Warehouse Manager  10+ years
128336     A        A4                                 Manager    8 years
128337     D        D2                     Sr Business Analyst     1 year
128338     B        B4                            Housekeeping    3 years
128339     A        A3                     Creative Strategist    3 years
128340     E        E2                                 Teacher    4 years
128341     D        D3                          Lead Installer    3 years
128342     C        C2                Administrative Assistant    3 years
128343     E        E2                                 Unknown   < 1 year
128344     B        B5                                 Unknown        NaN
128345     A        A3                                 Unknown   < 1 year
128346     A        A4         Heavy Equipment Delivery Driver    2 years
128347     A        A4                                     Dsp    4 years
128348     A        A4                                 Unknown        NaN
128349     C        C3                  Regional Sales Manager    2 years
128350     A        A1                  Multi-Media Specialist  10+ years
128351     C        C1                           Store Manager  10+ years
128352     A        A3                      Staff Psychologist    7 years
128353     E        E5                                 Unknown        NaN
128354     B        B1                      Routing Specialist    2 years
128355     B        B4                                 Unknown        NaN
128356     B        B4                      Clinical Associate    5 years
128357     E        E5                           Store Manager  10+ years
128358     C        C5                              Controller    5 years
128359     E        E5                                 Unknown   < 1 year
128360     A        A3                            Loan Officer     1 year
128361     B        B4                        Dental Hygienist  10+ years
128362     B        B3                                      Pt    4 years
128363     B        B3                    Technical Specialist  10+ years
128364     D        D1                              Bus Driver    6 years
128365     A        A5                   Compliance Consultant    3 years
128366     C        C1     Disability Employee Program Manager  10+ years
128367     C        C2              Technical Services Manager  10+ years
128368     D        D1                        District Manager    2 years
128369     C        C2                                 Unknown        NaN
128370     A        A4                          Budget Analyst  10+ years
128371     A        A5                                  Packer  10+ years
128372     A        A4                                  Driver  10+ years
128373     A        A1                Senior Lead Technologist  10+ years
128374     D        D5                                 Manager    9 years
128375     B        B4                           House Keeping    6 years

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01